/**
 * EsignatureService — ARCHITECTURE.md §4.2 / §9.5.
 *
 * Shared primitive for 21 CFR Part 11-style electronic signatures.
 * Every "critical action" that calls for password re-entry routes through
 * {@link EsignatureService.verifyAndHash} so the policy lives in exactly
 * one file:
 *
 *   - Approval-step act() when requires_e_signature = true
 *     (work_order/purchase_order/device_qc_final/invoice/... chains).
 *   - QC cert issue, sales invoice issue, stock write-off, device
 *     release (follow-on increments). Each of those call sites invokes
 *     verifyAndHash() directly — there is no middleware short-circuit.
 *
 * Contract:
 *   verifyAndHash({ userIdentityId, password, reason, actedAt })
 *     1. SELECT password_hash FROM user_identities WHERE id=$1 AND
 *        deleted_at IS NULL.
 *     2. bcrypt.compare against the stored hash. On miss, do a dummy
 *        compare against a fixed ciphertext so timing is constant.
 *     3. On success: return HMAC-SHA256(
 *          key = pepper,
 *          msg = reason || '\0' || userIdentityId || '\0' || actedAt
 *        ) hex-encoded.
 *     4. On failure: throw UnauthorizedError. No logging of the
 *        attempted password anywhere — not even at debug level.
 *
 * Hash scheme rationale:
 *   - HMAC rather than plain SHA-256 so an attacker who dumps the DB
 *     cannot brute-force short `reason` values against the stored
 *     hashes without the server-side pepper.
 *   - reason || userIdentityId || actedAt is sufficient for an auditor
 *     to recompute given the pepper (disclosed to them) and the row
 *     values (on the step / transition). No nonce is stored — the
 *     previous stopgap used a random nonce that was never persisted,
 *     rendering the hash unreproducible, which defeats re-verification.
 *     Replay within the same (user, timestamp) is impossible in
 *     practice because actedAt is an ISO-8601 string with ms precision
 *     generated by the server, not the client.
 *
 * Deliberate non-behaviour:
 *   - No rate-limit coupling in this service. The approvals POST route
 *     inherits the global rateLimit plugin (300/min per IP) which is
 *     the right layer for brute-force throttling.
 *   - No "remember for 30 min" cache. 21 CFR Part 11 requires re-entry
 *     for EACH critical action — caching defeats the point.
 *   - The raw password is never persisted, never logged, never held in
 *     a closure longer than the single bcrypt.compare await.
 */

import { createHmac } from "node:crypto";
import bcrypt from "bcrypt";
import type pg from "pg";
import { UnauthorizedError, ValidationError } from "@instigenie/errors";

export interface EsignatureServiceDeps {
  pool: pg.Pool;
  /**
   * HMAC-SHA256 key. Empty string is accepted for dev/test (degrades to
   * a plain SHA-256-keyed hash which is still collision-resistant but
   * re-computable from DB dump alone). Production requires ≥32 chars —
   * enforced by loadEnv() in apps/api/src/env.ts.
   */
  pepper: string;
}

export interface EsignatureVerifyArgs {
  /**
   * user_identities.id — the GLOBAL credential row, not users.id
   * (per-tenant profile). Callers get this from
   * requireUser(req).identityId. Must be non-null; handlers check
   * before calling and raise UnauthorizedError("no identity on
   * session") themselves if null.
   */
  userIdentityId: string;
  /** Plaintext password the user typed into the e-sig dialog. */
  password: string;
  /**
   * The textual statement the user agreed to ("Final QC pass —
   * serial ABC123"). Bound into the hash so the signature commits
   * to a specific action, not just "I typed my password once today".
   */
  reason: string;
  /**
   * ISO-8601 timestamp generated by the caller at the moment of
   * acting, recorded on the audit row. Bound into the hash so
   * replay of the (user, password, reason) tuple at a different
   * instant produces a different signature.
   */
  actedAt: string;
}

export interface EsignatureResult {
  /** HMAC-SHA256 hex. 64 chars. */
  hash: string;
}

/**
 * Constant-time dummy hash used when the identity row is missing so
 * the caller can't distinguish "user not found" from "wrong password"
 * via response-timing probes. Same scheme as the login path
 * (apps/api/src/modules/auth/service.ts).
 */
const DUMMY_BCRYPT_HASH =
  "$2b$10$1111111111111111111111111111111111111111111111111111u";

export class EsignatureService {
  constructor(private readonly deps: EsignatureServiceDeps) {}

  async verifyAndHash(args: EsignatureVerifyArgs): Promise<EsignatureResult> {
    if (!args.password) {
      // Defence-in-depth: contracts already reject empty strings, but a
      // caller passing undefined cast-through-any mustn't slip past.
      throw new ValidationError("e-signature password is required");
    }
    if (!args.reason) {
      throw new ValidationError("e-signature reason is required");
    }

    // 1. Look up password_hash for this identity. Cross-tenant — no RLS
    //    on user_identities. We only select the one column we need and
    //    filter deleted_at so a soft-deleted identity cannot e-sign.
    const { rows } = await this.deps.pool.query<{
      password_hash: string | null;
    }>(
      `SELECT password_hash
         FROM user_identities
        WHERE id = $1
          AND deleted_at IS NULL
        LIMIT 1`,
      [args.userIdentityId],
    );
    const passwordHash = rows[0]?.password_hash ?? null;

    // 2. Constant-time compare with dummy-on-miss.
    const ok = passwordHash
      ? await bcrypt.compare(args.password, passwordHash)
      : await bcrypt.compare(args.password, DUMMY_BCRYPT_HASH);
    if (!passwordHash || !ok) {
      // NOTE: no args.password in the log — ever.
      throw new UnauthorizedError("e-signature password incorrect");
    }

    // 3. HMAC-SHA256(pepper, reason || userIdentityId || actedAt).
    const mac = createHmac("sha256", this.deps.pepper);
    mac.update(args.reason);
    mac.update("\x00");
    mac.update(args.userIdentityId);
    mac.update("\x00");
    mac.update(args.actedAt);
    return { hash: mac.digest("hex") };
  }

  /**
   * Pure recomputation helper — useful for auditors and for Gate 42 to
   * assert determinism. Does NOT verify a password; only hashes.
   * Exposed as a static-ish method (via the service so the pepper stays
   * encapsulated) rather than a free function so callers can't forget
   * which pepper was used.
   */
  recomputeHash(args: {
    userIdentityId: string;
    reason: string;
    actedAt: string;
  }): string {
    const mac = createHmac("sha256", this.deps.pepper);
    mac.update(args.reason);
    mac.update("\x00");
    mac.update(args.userIdentityId);
    mac.update("\x00");
    mac.update(args.actedAt);
    return mac.digest("hex");
  }
}
